name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl

    - name: Configure kubectl
      run: |
        minikube start  # Start Minikube if it's not running
        kubectl config use-context minikube  # Set kubectl to use Minikube context

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl set image deployment/flask-app flask-app=${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        kubectl rollout status deployment/flask-app  # Wait for deployment to complete

    - name: Clean up
      if: always()
      run: |
        minikube stop  # Stop Minikube if you want to clean up after the job
